env:
  projects: "1_orbital-launchers-solution,2_orbital-launchers-javaconfig-solution,3_orbital-launchers-payload-configuration-solution,4_orbital-legacy-launchers-solution,5_orbital-launchers-mission-control-solution,6_orbital-launchers-launch-parameters-solution"

jobs:
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: ./mvnw clean test -B -pl $projects
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: ./mvnw clean package -DskipTests -B -pl $projects

on:
  push:
    branches:
      - main
  pull_request:
